### ISSUE TITLE
glpi 10 / show gantt diagram on glpi project

### ISSUE THREAD

**Issue by radhouanebo** [pluginsGLPI/gantt#3]
after installing gantt plugin on glpi 10 version and when trying to view gantt diagram of existing project i have the error :

**PHP User Warning (512): public/build/libs.js file not found from plugin gantt! in /var/www/html/glpi/src/Html.php at line 1874**

![Capture](https://user-images.githubusercontent.com/44923863/176704979-b41c9e7d-9bc3-4bf0-a234-42a2f2675ff7.JPG)

**Comment by cedric-anne** [comment]
Hi,

You probably install plugin source code only. You should install using the build archive.

Regards

**Comment by radhouanebo** [comment]
Hi,

I installed plugin through this steps:
- cloned gant plugin from git (git clone
https://github.com/pluginsGLPI/gantt.git)
- install plugin  (php bin/console glpi:plugin:install gantt)
- activate plugin (php bin/console glpi:plugin:activate gantt)

please what do you mean with You should install using the build archive

Best regards

Le ven. 2 sept. 2022 à 14:51, Cédric Anne ***@***.***> a
écrit :

**Comment by cconard96** [comment]
@radhouanebo, the built archives of official releases are here:
https://github.com/pluginsGLPI/gantt/releases
You can then extract them to your plugins folder like you do with the sources.

**Comment by radhouanebo** [comment]
Hi,
thank you it works now
best regards

Le lun. 5 sept. 2022 à 14:59, Curtis Conard ***@***.***> a
écrit :
