### ISSUE TITLE
Gannt order default by plan date start

### ISSUE THREAD

**Issue by ct0rm4n** [pluginsGLPI/gantt#65]
By Default fix gannt orderer by plan date start, 
I fix it and work fine

        $iterator = $DB->request([
            'FROM' => 'glpi_projects',
            'WHERE' => [
                'projects_id' => 0,
                'show_on_global_gantt' => 1,
                'is_template' => 0,
                'is_deleted' => 0
            ] + getEntitiesRestrictCriteria('glpi_projects', '', '', true),
            'ORDERBY' => 'glpi_projects.plan_start_date'

**Comment by cconard96** [comment]
Fixed by #66

**Comment by ct0rm4n** [comment]
Thanks!
