### ISSUE TITLE
Plugin Gantt Doesn't Work with GLPI Versions 10.0.1 and 10.0.2

### ISSUE THREAD

**Issue by itrohr** [pluginsGLPI/gantt#8]
Hello, 

After install gantt pluin it appear in the project tools, but show a blank tab info with PHP Warning in the apache error logs:

PHP Warning:  public/build/libs.js file not found from plugin gantt! in /var/www/localhost/htdocs/glpi/src/Html.php on line 1874

![image](https://user-images.githubusercontent.com/8867240/189333129-bec3ca9b-0f6c-49f8-b028-ffbed2da9860.png)

Could you help to solve this issue?

Thanks
Rodolpho Rohr

**Comment by Daeloran** [comment]
Same issue with GLPI 10.0.5 :(
But with this:
PHP Warning:  public/build/libs.js file not found from plugin gantt! in /var/www/html/glpi/src/Html.php on line 1902
