### ISSUE TITLE
project/task/milestone are created on root entity only

### ISSUE THREAD

**Issue by Lanoixdecoco** [pluginsGLPI/gantt#9]
Hello,
Im not native english, i will do my best.

This is an example : 
I have an entity A (root>Entity A)
I have an user B that is Admin on root>Entity A (and nothing more)
I have a project C on root>Entity A

Everything is OK when i use only GLPI vanilla features

When i use TASKS tab in project C with user B on root>Entity A, and create a taskwith it, they are created with root>Entity A entity
- Then, they are accessible, because user B on root>Entity A have permissions on root>Entity A entity

The problem is here : 
When i use GANTT tab in project C with user B on root>Entity A, and create a project/task/milestone with it, they are created with root entity
- Then, they are not accessible, because user B on root>Entity A have no permissions on root entity, only root>Entity A
- They are still accessible with accounts that have entity root (like GLPI superadmin, or any account that is Admin on root entity)

Expected behaviour :
When i use GANTT tab in project C with user B on root>Entity A, and create a project/task/milestone with it, they are created with root>Entity A entity

**Comment by AutajonTech-LP** [comment]
Hello, 
I confirm having the same issue. When creating a task/milestone from the GANTT view, the task/milestone is created by default on the root entity and not on the entity of the user.
I've done some tests using differents entities and users. The task/milestone is always created on the root entity and never created on the user entity. Even when the user has no rights on the root entity so the user can not open the task.
Expectation is as decribed : create the task/milestone using the entity of the user.
Best regards

**Comment by Pieval44** [comment]
GLPI Version 10.0.6
Gantt plugin : 1.0.1

Je confirme le même problème.
les taches créées depuis le GANTT sont rattaché à la Racine au lieu de l'entité du projet.

**Comment by cedric-anne** [comment]
Hi,

Could you check if #17 fixes this issue?

**Comment by AutajonTech-LP** [comment]
Hi,
I've done tests and confirm that the problem is solved.
Thank you !
